"""addedf votes

Revision ID: bbc154c096b8
Revises: 9c8bff203a71
Create Date: 2024-12-12 10:42:54.273892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc154c096b8'
down_revision = '9c8bff203a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('downvotes')
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
